--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Lmi FW12
version: lmi
steps:
 - name: Nexus Lmi FW12
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null lmi
     
--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Alioth
version: alioth
steps:
 - name: Nexus Alioth
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null alioth

--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Lmi FW13
version: lmi
steps:
 - name: Nexus Lmi FW13
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null fw13

--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Apollo
version: apollo
steps:
 - name: Nexus Apollo
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null apollo
